FROM python:3.6-alpine
RUN pip install --no-cache-dir pip==18.0
RUN apk add --update git gcc libc-dev libxslt-dev libpq-dev
RUN pip install --no-cache-dir pipenv==2018.11.26
WORKDIR /data/
COPY src/Pipfile Pipfile
RUN pipenv --three install
COPY src/ .
ENTRYPOINT [ "pipenv", "run" ]
CMD [ "python", "main.py" ]
